[env]
DISCIPLINE_PAM_MODULE_DATA_NAME_ENVIRONMENT_VARIABLE_NAME = "DISCIPLINE_PAM_MODULE_DATA_NAME"
DISCIPLINE_INSTALLATION_DIRECTORY_ENVIRONMENT_VARIABLE_NAME = "DISCIPLINE_INSTALLATION_DIRECTORY"

DISCIPLINE_INSTALLATION_DIRECTORY = "TODO"
DISCIPLINE_USER_ACCOUNT_BLOCKED_MESSAGE = "TODO"
DISCIPLINE_PAM_MODULE_DATA_NAME = "TODO"
PAM_CALL_TIMEOUT = "TODO"