[package]
name = "discipline_daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
libc = "0.2.177"
rusqlite = "0.37.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
uuid = { version = "1.18.1", features = ["v4"] }
